### ISSUE TITLE
Fix this.

### ISSUE THREAD

**Issue by Secret-chest** [C1710/blobmoji#107]
Here's how the [✅](https://emojipedia.org/check-mark-button/) emoji should look:
![image](https://user-images.githubusercontent.com/74449186/156877502-ab492d2a-ca27-4973-8b1b-a90aec82dcbc.png)
It's a check mark _button_.

But it's just a bare white checkmark here. Please fix.

**Comment by C1710** [comment]
3cce203cebeb07c62e133d7f845b5d0557dde055

**Comment by Secret-chest** [comment]
Thanks ;)
