### ISSUE TITLE
Change Exploding Face, Grinning Face, Vomiting Face, Faces with hands

### ISSUE THREAD

**Issue by Bronnel721** [C1710/blobmoji#136]
I know that you're probably annoyed about these issues I've made, but I can't do anything about it since I can't make any more changes. Also, change the grinning emoji to look more like this:
![image](https://github.com/C1710/blobmoji/assets/92538982/9e1e3d78-6206-4320-92f7-6dbb33b055bf)
Also, also, use this ZIP file for the blobs with hands: 
[Emojis With Hands.zip](https://github.com/C1710/blobmoji/files/11912353/Emojis.With.Hands.zip)

**Comment by Bronnel721** [comment]
@C1710, can you please fix this? I know you're probably tired of this, but I didn't know that the exploding face would look weird. Also, try to change how the vomit on the vomit emoji looks like.

**Comment by C1710** [comment]
> Also, change the grinning emoji to look more like this:
> ![image](https://github.com/C1710/blobmoji/assets/92538982/9e1e3d78-6206-4320-92f7-6dbb33b055bf)

No, I won't change that because the current version looks significantly better.
I can't currently view the hand emojis on my phone (I don't have an SVG viewer installed) and I won't add changes from a zip file. I am aware of the issues with `face with peeking eye` though and might still revert the hand design there.

**Comment by Bronnel721** [comment]
> No, I won't change that because the current version looks significantly better.

Are you talking about the exploding face or the grinning face emoji?
Edit: Now I know.

**Comment by Bronnel721** [comment]
Never mind on the .zip file. I could try other ways, but I don't know if I should do this. Also, these are the changes:
![emoji_u1f92b](https://github.com/C1710/blobmoji/assets/92538982/fc1c2971-8c67-414d-bdbb-1a301e58e6f9)
![emoji_u1f92d](https://github.com/C1710/blobmoji/assets/92538982/333619e8-f096-479a-85bf-22225338d44c)
![emoji_u1f971](https://github.com/C1710/blobmoji/assets/92538982/b18534b2-3ee2-4b6b-801f-da79e723dbde)
![face with open eyes and hand over mouth](https://github.com/C1710/blobmoji/assets/92538982/b9c9213e-c0b3-4e00-8309-f3524a9b8856)
![face with peeking eye](https://github.com/C1710/blobmoji/assets/92538982/84837363-6104-448c-b414-2169049495ad)

**Comment by C1710** [comment]
No, I won't apply those changes. The hands look fine as they are. I also just fixed peeking face to use the correct hands again.
For Exploding Face, I think only the colors needed some updating and the eyes had weird lines around them, which I also fixed.
I did update the vomit though.

**Comment by Bronnel721** [comment]
>  I think only the colors needed some updating and the eyes had weird lines around them, which I also fixed.

That was exactly what I made this issue for.

> No, I won't apply those changes. The hands look fine as they are.

I only changed them because the other emojis with hands have a thick border while the ones designed by you have a thin border.
