### ISSUE TITLE
Radio button/checkbox

### ISSUE THREAD

**Issue by Madis0** [C1710/blobmoji#16]
The radio button should look more like a radio button and less like a broken miscolored target.
`U+1F518` :radio_button: [Emojipedia](https://emojipedia.org/radio-button/)
In my opinion, it should also look more consistent with the checkbox, like Apple does.
`U+2611 U+FE0F` :ballot_box_with_check: [Emojipedia](https://emojipedia.org/ballot-box-with-check/)
Personally I'd just steal it from [Material guidelines](https://material.io/guidelines/components/selection-controls.html#selection-controls-checkbox) :stuck_out_tongue: 
![](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bx4BSt6jniD7T2xGbGo0cUlPVG8/components-switches-check1.png)
![](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bx4BSt6jniD7Z1NaaXh2ZkpDRkE/components-switches-radio1.png)

**Comment by C1710** [comment]
I think the radio button could be improved as it doesn't clearly show a radio button.  
However, I don't think it would be good to simply take these normal buttons since it could be a bit confusing to see an actual radio button inside some text, so it should be recognizable as an emoji...

**Comment by C1710** [comment]
These are the radio button and checkbox now. They use the same color:
https://github.com/C1710/blobmoji/blob/emoji13/svg/emoji_u1f518.svg

https://github.com/C1710/blobmoji/blob/emoji13/svg/emoji_u2611.svg

**Comment by C1710** [comment]
I think I'll close this issue for now.
