### ISSUE TITLE
Emojis that need recoloring

### ISSUE THREAD

**Issue by Madis0** [C1710/blobmoji#18]
A meta bug for emojis that need to be recolored in order to be platform-consistent.

**Comment by Madis0** [comment]
* `U+1F4A0` :diamond_shape_with_a_dot_inside: [to blue](https://emojipedia.org/diamond-shape-with-a-dot-inside/)
* `U+1F50B` :battery: [to green](https://emojipedia.org/battery/)

**Comment by C1710** [comment]
I'm not really sure if every emoji has to have the same color as on any other platform. I'll consider this for the future but I guess it will have a little bit lower priority.

**Comment by Madis0** [comment]
`U+1F4A4` :zzz: [to blue](https://emojipedia.org/sleeping-symbol/)

**Comment by Madis0** [comment]
The Red Cross abuse [has been](https://emojipedia.org/hospital/) [fixed](https://emojipedia.org/ambulance/) in Pie for 🏥 🚑. I would prefer a Switzerland flag like Microsoft does.

**Comment by rileyinman** [comment]
`U+1F621` 😡 should be more fully [red](https://emojipedia.org/pouting-face/) since the lack of color somewhat muddles the meaning.

**Comment by C1710** [comment]
Sorry, thought the furious emoji was an own issue. Added a changed version, font is not yet updated.

**Comment by C1710** [comment]
All pictures are now updated (💠🔋💤🏥🚑😡)
