### ISSUE TITLE
possibly change family name?

### ISSUE THREAD

**Issue by redg3ar** [C1710/blobmoji#20]
This is a great project, but i think that the font family name should be changed to make the difference clear. 
noto-emoji-blobs might be a good choice?

P.S. the [blobs discord server](blobs.gg) has a lot of good fanmade blobs that you might find useful!

**Comment by redg3ar** [comment]
It looks like it does have a custom family name and gnome font viewer just confused me, ill close this issue but I highly reccommend checking out the discord server

**Comment by C1710** [comment]
Yeah, I've actually changed the font family's name some time ago but I had similar issues with this Gnome font viewer 😂  
I'll have another look at it soon(ish)™

**Comment by Jop-V** [comment]
Link for the Discord channel?
