### ISSUE TITLE
Problems with Fedora 28

### ISSUE THREAD

**Issue by C1710** [C1710/blobmoji#26]
So apparently Fedora 28 includes emoji by default!  
Unfortunately they went for Noto Emoji. And you can't uninstall it without uninstalling like the whole system.  
So I guess I'll have to fix this somehow.  
Unfortunately I don't have very much time for the next 1-2 months so a fix might take a bit longer...

**Comment by igalic** [comment]
the easiest would be to overwrite the file.
i did the same on Ubuntu:

After installing `fonts-noto-color-emoji`, i replaced `/usr/share/fonts/truetype/noto/NotoColorEmoji.ttf` with the file i had just built.
This has the advantage of ensuring that the correct config is applied, but the disadvantage of that file running the risk of being overwritten by the package manager on a (system) upgrade

But, anyway, the "correct configuration" (on Debian/Ubuntu) is provided by https://gist.github.com/igalic/74370cad53264c306c34672ec5945559 and pretty much always enabled

**Comment by C1710** [comment]
(I'm not sure whether this is still relevant)
