### ISSUE TITLE
Android P new emoji

### ISSUE THREAD

**Issue by Madis0** [C1710/blobmoji#27]
Android P preview got [some new emoji](https://blog.emojipedia.org/inclusive-emojis-coming-back-to-android/). Full changes aren't listed on Emojipedia yet AFAIK, but notably: 

- default family and couple is gender-inclusive 
- new hairstyles 
- at least 8 emoji from v11
- some emoji got visual changes  

I'm aware Blobmoji supports Emoji 11 already, but you may want to use this to update your designs, if needed.

**Comment by NanhuGITHUB** [comment]
Also MS Added Emoji 11 To Insider Preview Emoji

**Comment by Madis0** [comment]
[Full changelog for Pie emoji](https://blog.emojipedia.org/android-9-0-emoji-changelog/)
