### ISSUE TITLE
The original ☺  needs rosy cheeks

### ISSUE THREAD

**Issue by Madis0** [C1710/blobmoji#34]
[All platforms have now added](https://emojipedia.org/white-smiling-face/) rosy cheeks to the "White Smiling Face" ☺️, therefore this project should do that as well to prevent any confusion.

**Comment by Madis0** [comment]
>These "rosy cheeks" are already there and they have always been there.

They are? In my device I see the [Android 7.0 version](https://emojipedia.org/google/android-7.0/white-smiling-face/) - a slightly larger smile of [slightly smiling face](https://emojipedia.org/slightly-smiling-face/) 🙂

![](https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/160/google/56/white-smiling-face_263a.png)

![screenshot](https://user-images.githubusercontent.com/8611110/48968304-31b8fb80-eff6-11e8-865a-2e76c9d915e2.png)

**Comment by C1710** [comment]
Wait, that is actually a different emoji than '😊'...

**Comment by Madis0** [comment]
Made a (bad) table to show what I mean. As always, Apple is to blame for ruining the original intent of this emoji, but as with the gun, there should be an update to clarify it's current meaning.
![iblameapple](https://user-images.githubusercontent.com/8611110/48968510-3337f300-eff9-11e8-96f6-c3f64022004c.png)
