### ISSUE TITLE
Darker mouth if teeth are shown

### ISSUE THREAD

**Issue by Madis0** [C1710/blobmoji#35]
I've noticed that in small fonts, the mouths aren't as legible as in other emoji sets.

For example, the widely used [grinning face](https://emojipedia.org/grinning-face/) 😀 may seem like it is more about the white teeth, rather than the smile itself.

Similarly, [the tears of joy](https://emojipedia.org/face-with-tears-of-joy/) 😂  slightly look like fangs due to lack of contrast.

Which dark color to use, though, is up to you. I'd prefer red (Samsung) or black/gray (Google, EmojiOne, Microsoft), not yellow (Apple, WhatsApp, Twitter).

Edit: Not all mouths need to be changed, only those that show teeth.

**Comment by C1710** [comment]
Erm, somehow I missed this one...  
I am still trying to figure out a better way to show the emojis with teeth - not only the color (which I personally haven't experienced any problems with) - but rather with their overall style. I don't really like this white band as it is now, but I don't know any alternative yet...
