### ISSUE TITLE
Add transgender pride flag emoj

### ISSUE THREAD

**Issue by igalic** [C1710/blobmoji#38]
copying this from https://github.com/twitter/twemoji/pull/337

The latest version of WhatsApp includes the [transgender pride flag](https://en.wikipedia.org/wiki/Transgender_flags#Transgender_Pride_Flag) as [emoji ZWJ sequence](https://emojipedia.org/transgender-pride-flag/). It consists of U+1F3F3 (WAVING WHITE FLAG), U+FE0F (VARIATION SELECTOR-16), U+200D (ZERO WIDTH JOINER), U+26A7 (MALE WITH STROKE AND MALE AND FEMALE SIGN).

On WhatsApp it looks like this:
![](https://camo.githubusercontent.com/33956cbd1bd59b564796f12f6d90381864e297e9/68747470733a2f2f656d6f6a6970656469612d75732e73332e6475616c737461636b2e75732d776573742d312e616d617a6f6e6177732e636f6d2f7468756d62732f3136302f77686174736170702f3138362f7472616e7367656e6465722d70726964652d666c61675f31663366332d666530662d323030642d323661372e706e67)

Several people on Twitter already [started using it](https://twitter.com/search?q=%F0%9F%8F%B3%EF%B8%8F%E2%80%8D%E2%9A%A7) since [2017](https://twitter.com/m_u_s_h_r_o_o_m/status/938876974151421953), so it would be great if Twemoji could add official support as well. Transgender activists are already requesting for this emoji for a long time, it was one of the most-requested emoji of [2018](https://blog.emojipedia.org/top-emoji-requests-2018/) and of [2017](https://blog.emojipedia.org/top-emoji-requests-2017/).

Several news articles have already been published about this new emoji in WhatsApp:

- [Transgender Pride Flag Emoji Hidden in Latest WhatsApp](https://blog.emojipedia.org/transgender-pride-flag-emoji-comes-to-whatsapp/) at Emojipedia

- [Hey Sis, the Trans Pride Flag Emoji Is Here](https://www.out.com/tech/2019/3/06/hey-sis-trans-pride-flag-emoji-here) at Out Magazine

- [A transgender Pride flag emoji exists—here’s how to get it](https://www.pinknews.co.uk/2019/03/06/transgender-pride-flag-emoji-how-get-it/) at PinkNews

- [There’s a secret WhatsApp trick which ‘lets you use a hidden transgender pride flag emoji in messages’](https://metro.co.uk/2019/03/06/secret-whatsapp-trick-lets-get-transgender-pride-flag-emoji-8836030/) at Metro

**Comment by C1710** [comment]
It's already included in the Emoji 12 branch 😉

**Comment by C1710** [comment]
Wait.... Apparently it's not working yet. I'll take a look at it.

**Comment by C1710** [comment]
Hm... Seems like it's more complicated than I thought...  
It _was_ missing in the EmojiCompat font, but it still doesn't work although I added it 🤔

**Comment by C1710** [comment]
So, it _is_ included in the regular font, but as I mentioned, it doesn't seem to work in the EmojiCompat font...

**Comment by bb010g** [comment]
❤️
Thanks for being so quick to respond on this.

**Comment by C1710** [comment]
Fixed in b330049.  
Since I accidentally copied the font file to the wrong directory, I'm not quite sure what the problem was...  
However, it seems to work now.

**Comment by igalic** [comment]
any idea when the 12 branch will be released?

**Comment by C1710** [comment]
@igalic I'm not quite sure when I'll merge it into master, but if you want to, you can already use it of course (probably; I don't know in which context you want to use it 😅): https://github.com/C1710/blobmoji/tree/emoji12
