### ISSUE TITLE
rofimoji won't use Blobmoji

### ISSUE THREAD

**Issue by Silent-Hunter** [C1710/blobmoji#41]
For some reason, Blobmoji won't work in this program even though it's supposed to support color emojis. I'm not sure if it's an issue with Blobmoji, or rofimoji. Even a lot of the black and white emoji are missing. Isn't Blobmoji supposed to have those as a fallback?

https://github.com/fdw/rofimoji

**Comment by C1710** [comment]
No, AFAIK there is no B/W fallback. There was a `NotoEmoji.ttf` which (I think) was a b/w font, but since the scripts didn't generate them, I removed it (I think someone in another issue suggested that).

**Comment by C1710** [comment]
But it _is_ kinda strange that it officially supports Noto Emoji on which Blobmoji is based on 🤔  
So it _shouldn't_ cause any problems...

**Comment by Silent-Hunter** [comment]
Yeah I don't know why it doesn't work. I also submitted a bug for rofimoji, in case that's the issue. I wonder if I did something wrong in my "~/.config/fontconfig/fonts.conf" file though.

**Comment by C1710** [comment]
So I just tried it on my (rather old) Fedora 28 installation which has Blobmoji working (more or less, since it seems to prefer the current Noto Emoji which I can't uninstall without breaking certain dependencies), Rofimoji didn't complain about anything and seems to work fine...

**Comment by Silent-Hunter** [comment]
The rofimoji developer says it's definitely a font issue but since he doesn't use debian he says he can't help. He says it's neither easy nor straightforward. The stupid thing is even using a program name match in my font config won't force rofimoji to use the blobmojis.

`    <match target="pattern">
    <test name="prgname" qual="any">
      <string>rofi</string>
    </test>
    <edit name="family" mode="prepend_first">
      <string>Noto Emoji</string>
    </edit>
  </match>`

**Comment by C1710** [comment]
By the way, what actually _happens_? Does it crash with some error message, are the emojis just invisible or empty boxes or do you see another emoji style?  
And does it work in other programs like your browser, file manager, etc.?

**Comment by Silent-Hunter** [comment]
Blobmoji works in Vivaldi and Discord, but nothing else that I've seen.

rofimoji looks like this, for me.

![rofi-2019-06-29-1520](https://user-images.githubusercontent.com/3732535/60405330-40572a80-9b64-11e9-92d0-6c42b72f7117.png)

The good news is I can still use it, it just doesn't look nice.

**Comment by Silent-Hunter** [comment]
Okay, for some reason Blobmoji doesn't show up when I run `fc-list`. But it still works in Vivaldi and Discord.

Here's my fontconfig.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">

<fontconfig>
 <alias>
   <family>sans-serif</family>
   <prefer>
     <family>Blobmoji</family>
   </prefer>
 </alias>

 <alias>
   <family>serif</family>
   <prefer>
     <family>Blobmoji</family>
   </prefer>
 </alias>

 <alias>
  <family>monospace</family>
  <prefer>
    <family>Blobmoji</family>
   </prefer>
 </alias>
</fontconfig>
```

**Comment by C1710** [comment]
But color/emoji fonts work in general?  
Have you tried any other emoji font - perhaps installed as a package (for example [this](https://github.com/eosrei/twemoji-color-font#install-on-ubuntu-linux) build of Twemoji)?  
It might be possible that your OS in general doesn't support color fonts, which is relatively likely, since Vivaldi and Discord probably bring their own font rendering libraries with them.

**Comment by C1710** [comment]
There is a [Reddit-post](https://www.reddit.com/r/debian/comments/6k8qh3/problem_enabling_color_emoji_in_chrome/) about this, but I'm not sure if that fits to your issues :/

**Comment by Silent-Hunter** [comment]
The rofimoji developer suggested I type `fc-match 'Blobmoji'`, and I don't think this is right.

```
kavus@micropc:~$ fc-match 'Blobmoji'
DejaVuSans.ttf: "DejaVu Sans" "Book"
```

**Comment by C1710** [comment]
Erm, that indeed looks... _really_ strange...  
But honestly I don't have any idea. And I don't think I have ever even _typed_ "DejaVu Sans" since I started this fork...

**Comment by Silent-Hunter** [comment]
It looks like my system is simply refusing to use Blobmoji or Noto Color Emoji. `fc-list` doesn't show them. It's really weird that it works in Vivaldi and Discord though. Even if they have their own font rendering libs, they shouldn't be able to use a font the system doesn't recognize should they?

**Comment by C1710** [comment]
My guess is that they just look at the font directories directly and not at the fontconfig...

**Comment by Silent-Hunter** [comment]
Yeah, with no local fontconfig in my home directory, Blobmoji still works in Vivaldi and Discord. I'm unsure why the non-color Noto Emoji gets picked up by the fontconfig though. And so does EmojiOne/Titter Color Emoji. I'm convinced it's my system though. Debian 10 comes out in a few days, maybe that will fix it.
