### ISSUE TITLE
Some Android 10 flags missing 

### ISSUE THREAD

**Issue by Madis0** [C1710/blobmoji#44]
🇧🇱 https://emojipedia.org/flag-for-st-barthelemy/

🇷🇪 https://emojipedia.org/flag-for-reunion/

🇹🇫 https://emojipedia.org/flag-for-french-southern-territories/

🇧🇶 https://emojipedia.org/flag-for-caribbean-netherlands/

🇲🇶 https://emojipedia.org/flag-for-martinique/ (incorrect snakes)

**Comment by C1710** [comment]
The flags are all included in the font. The images are (I think using a script) taken from Wikipedia.

**Comment by Madis0** [comment]
Well, they render but not as other emoji sets but rather as France/Netherlands flags.

**Comment by C1710** [comment]
Yeah, that's because these are the official flags ^^

**Comment by Madis0** [comment]
Fair enough, but Martinique is still incorrect.

**Comment by Madis0** [comment]
In that case you forgot to use the French flag for Martinique.

**Comment by C1710** [comment]
Resolved with Emoji 13.1 (at least as far as I can see)
