### ISSUE TITLE
Weird pinching hand

### ISSUE THREAD

**Issue by Madis0** [C1710/blobmoji#45]
https://emojipedia.org/pinching-hand/

The pinching hand emoji has a weird position of the fingers and the index finger is too long.

**Comment by C1710** [comment]
Yeah, I am totally aware that it looks really, really bad.  
The reason is simply: I am really, really bad at designing something complex as hands :D  
Maybe I'll include a modified version of the Noto pinching hand (which wasn't available at the time)...

**Comment by C1710** [comment]
Here's a solution based on Google's design.

![emoji_u1f90f](https://user-images.githubusercontent.com/10349490/64885642-ee9f4600-d664-11e9-8ed9-7e0d655a395f.png)

**Comment by C1710** [comment]
And another question is: Which direction? Google and Microsoft point to the left, Twitter and Emojipedia point to the right.

**Comment by Madis0** [comment]
For simplicity's sake, keep the same direction as Google.
