### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by dasJ** [C1710/blobmoji#48]
Nototools was ported to Python 3: googlefonts/nototools#488
Also upstream switched: googlefonts/noto-emoji#267

**Comment by dasJ** [comment]
Oh also fonttools has pledged to not support Python 2 in 2020: https://python3statement.org/

**Comment by C1710** [comment]
I've updated the scripts to the ones Noto Emoji uses, which should be Python 3-ready.  
Makefile is also updated.
