### ISSUE TITLE
AssetEmojiCompatConfig can not load Metadata

### ISSUE THREAD

**Issue by jemshit** [C1710/blobmoji#49]
Hi, i am trying to use `AssetEmojiCompatConfig` with EmojiCompat library to load custom font located under `main/assets/customfont.ttf`.
```kotlin
val config = AssetEmojiCompatConfig(this, "customfont.ttf")
config.registerInitCallback(object:EmojiCompat.InitCallback(){
            override fun onInitialized() {
                super.onInitialized()
            }

            override fun onFailed(throwable: Throwable?) {
                super.onFailed(throwable)
            }
})
EmojiCompat.init(config)
```

Inside `AssetEmojiCompatConfig`, at line 107, i see error `IOException: Can not read metadata`. It is raised in `MetadataRepo.java` (of EmojiCompat) at line 130. I think Typeface is created, but can not create Metadata.

The font i use is downloaded from fontello.com (choose 1 random icon, then download font zip file). I have tried assigning different unicode values for custom emojis, still same problem. Any clues?

**Comment by C1710** [comment]
There are two problems with your font (I think):
1. Fontello seems to create a different kind of color fonts which Android is not able to use.
2. EmojiCompat requires a special table that actually contains the EmojiCompat metadata (honestly, I don't know its purpose. I only know that it is required), which is also not included in this font.

By the way, the library is now available in its [own repository](https://github.com/C1710/FilemojiCompat) and all the features of `AssetEmojiCompatConfig` are now included in `FileEmojiCompatConfig` (the advantage of that one is that your users can simply use their own fonts if they wish to).

**Comment by jemshit** [comment]
Let me try `FileEmojiCompatConfig`, it seems it creates Metadata from Stream

**Comment by C1710** [comment]
I don't think that it makes any difference in this case as the fonts created by Fontello don't include any metadata.  
However, using the Unicode data tables you could try to add the required metadata to your font (I have written some instructions about this: https://github.com/C1710/blobmoji/wiki/EmojiCompat-support#how-do-you-build-the-font).

**Comment by C1710** [comment]
However, I don't know how this script (or anything here) works for non-color fonts.

**Comment by jemshit** [comment]
Ok, thanks
