### ISSUE TITLE
Q: Difference between compat and normal?

### ISSUE THREAD

**Issue by Oymate** [C1710/blobmoji#59]

**Comment by C1710** [comment]
The "compat" version is intended to be used with the `EmojiCompat` library that is used in a few Android apps (and in even fewer apps you can actually choose your own font).
So basically unless you develop Android apps or if you're using the Mastodon client Tusky (which supports this), the normal font is probably the better choice.

Although I _think_, you can also use the compat version for everything else...

**Comment by Oymate** [comment]
I do use tusky, so thanks!
