### ISSUE TITLE
Underlined 100 emoji showing as underlined 42

### ISSUE THREAD

**Issue by twentypeak** [C1710/blobmoji#6]
Title says it all. I am using the magisk module on a OnePlus 5t. Is this a bug or is there a reason for it?

**Comment by C1710** [comment]
Well, this was an easter egg I made when I haven't published this font.
I'll fix it in the next few hours 😅
42 is actually the answer to the life, universe and everything :D

**Comment by C1710** [comment]
26ab470ddd7740bfb5c939800f9adec4d7517b0f changed this behavior. However, I'll re-add the 42 emoji as a new ZWJ sequence 😁
