### ISSUE TITLE
Still no support of unicode 13?

### ISSUE THREAD

**Issue by choukawaii** [C1710/blobmoji#61]
Slow but sure, I found some new emojis that not replaced by blob moji. Kind of annoying tho.

**Comment by Measureless** [comment]
Still waiting...

**Comment by Zodigram** [comment]
The maintainer probably has their own life and can't just drop everything to work full time on this. Let them get to it when they get to it

**Comment by DavidBerdik** [comment]
If you are willing to sacrifice consistency for completeness, you can use my Blobmoji build here: https://github.com/DavidBerdik/blobmoji-font/releases/tag/blobmoji-13.1-pre

**Comment by choukawaii** [comment]
> If you are willing to sacrifice consistency for completeness, you can use my Blobmoji build here: https://github.com/DavidBerdik/blobmoji-font/releases/tag/blobmoji-13.1-pre

Used it for a while and now wondering if the 5 non-blob-ed emojis is already blob-ed or no.

**Comment by DavidBerdik** [comment]
> Used it for a while and now wondering if the 5 non-blob-ed emojis is already blob-ed or no.

I have not checked the repository since I published that build, but at the time, they had not been blobbed yet. Unless I missed something from a quick glance at the repository again, that is still the case.

**Comment by C1710** [comment]
[As there is a prerelease now](https://github.com/C1710/blobmoji/issues/58#issuecomment-864456740), I'll close this issue (especially as it's actually a duplicate anyway).
