### ISSUE TITLE
Disguised Face is not even shown.

### ISSUE THREAD

**Issue by choukawaii** [C1710/blobmoji#71]
https://github.com/DavidBerdik/blobmoji-font/releases/tag/blobmoji-13.1-pre

https://emojipedia.org/disguised-face/

You can check that the disguised face is not even present.

**Comment by C1710** [comment]
I just checked and it looks like I forgot to correct the typo/to push it.

However I don't really understand what this has to do with the other repository?

**Comment by choukawaii** [comment]
> However I don't really understand what this has to do with the other repository?

Just a reference, since that repository have 5 un-blobbed emoji, yet one of them is disguised face.

**Comment by C1710** [comment]
It's now corrected. You can find the rest of the progress in #58
