### ISSUE TITLE
Input types need to be solid

### ISSUE THREAD

**Issue by Madis0** [C1710/blobmoji#8]
The following input types:

`U+1F524` :abc: `U+1F523` :symbols: `U+1F522` :1234: `U+1F521` :abcd: `U+1F520` :capital_abcd:

should have a solid blue background and be inside a square. [Emojipedia](https://emojipedia.org/search/?q=input)

**Comment by C1710** [comment]
I just did these changes and I'll upload them when the fonts are ready to the [`redesign`](https://github.com/C1710/blobmoji/tree/redesign) branch.
