### ISSUE TITLE
New, Non-RGI/custom (ZWJ-)sequences

### ISSUE THREAD

**Issue by MarcoMahone721** [C1710/blobmoji#82]
I need new ZWJ-sequences in this font.

**Comment by C1710** [comment]
Which ones? As far as I can see, all sequences up to 13.1 are present...

**Comment by MarcoMahone721** [comment]
A 😀+🎧 so it can equal the blob emoji to wear headphones. But that's not it.

**Comment by C1710** [comment]
> 
> 
> A 😀+🎧 so it can equal the blob emoji to wear headphones.

Something like that could be done once extension packs are finished, but I these things are rather low priority now and actually work better as a discussion...
