### ISSUE TITLE
This emoji needs to be fixed.

### ISSUE THREAD

**Issue by MarcoMahone721** [C1710/blobmoji#86]
The man in manual wheelchair needs to be fixed, as well as the other skin tones. Because that is a woman, not a man. It's supposed to be a man, not a woman.

**Comment by C1710** [comment]
Fixed in 461809616e5aff0e1bf32aacd9552168b8a52d3f

**Comment by MarcoMahone721** [comment]
Okay. Which version of the font did you fix it. Also did you publicly release it yet?

**Comment by C1710** [comment]
> 
> 
> Okay. Which version of the font did you fix it. Also did you publicly release it yet?

The one on the [`emoji-13-1`-branch](https://github.com/C1710/blobmoji/tree/emoji13-1)

**Comment by Limaeoha** [comment]
Emoji loudly
