### ISSUE TITLE
Overridden System Emojis

### ISSUE THREAD

**Issue by nolombic** [C1710/blobmoji#95]
To keep it shot:

Installing BlobmojiWindows.ttf (release 14.0, installed on Win10 Pro 21H1) overrides Segoe UI Emoji as a "Regular"-style (normally Segoe UI Emoji only offers a "Standard"-style).
Consider adjusting the metadata so it won't install as "Segoe UI Emoji" but maybe as "Noto Emoji" or "Blob Emoji" or similar instead.

![image](https://user-images.githubusercontent.com/67807622/129971637-62435d7d-108b-46d2-bc1f-f0e71dd14810.png)

**Comment by C1710** [comment]
That should be fairly easy. I'll do it later today

**Comment by nolombic** [comment]
btw: If you've got a new font file ready and need someone to test it out I'd be willing to take it for a test drive.

**Comment by C1710** [comment]
Whoops, I totally forgot to mention it, the latest version in the `emoji14` branch has both an override/default replacement and non-override version 😅

Sorry

**Comment by nolombic** [comment]
# Testing Results

## Installation

> - Pre-Installation Name Check: ✔  
>   ![image](https://user-images.githubusercontent.com/67807622/130324882-e0543ed2-c949-4744-832f-97518dbf8b90.png)  
> - Post-Installation Non-Override Check: ✔  
>   ![image](https://user-images.githubusercontent.com/67807622/130325079-8f9ae6a6-9f13-4066-9455-d35f114e911e.png)  

## Usage

> - Windows Settings Preview: ❌  
>   ![image](https://user-images.githubusercontent.com/67807622/130325117-315c49a5-5af0-4dd4-8657-ec11403e89e4.png)  
> - Windows Settings Font Test: ✔  
>   ![image](https://user-images.githubusercontent.com/67807622/130325042-41c94324-8240-406b-81c9-f80a6e4aa4c6.png)  
> - Affinity Suite: ❌  
>   ![image](https://user-images.githubusercontent.com/67807622/130325232-8938fb14-8ef5-43e4-bb98-95874684cf5c.png)  
>   Font completely unavailable  
> - Paint: ❔  
>   ![image](https://user-images.githubusercontent.com/67807622/130325325-4035ebea-ba05-4735-a371-56cc003e256e.png)  
>   Name field empty in list but displayed correctly when used - probably why Affinity can't find it.  
>   Defaults to Segoe UI Emoji when used.

**Comment by C1710** [comment]
- I'm not sure whether Affinity supports CBDT/CBLC.  
  But you should always be able to use the SVGs, they are created with that software, after all 😅

- About the preview: I have an entry for sample characters, but maybe it's the wrong records or so...

- About Paint: Well, as you can see, it displays the name of the font in the font itself and as this one does not provide "B", "l", "o", "m", etc. the name cannot be shown.

Since the font does not override the system font anymore, I'll close this issue.
